print("content-type:text/html\r\n\r\n", end = "")

print("<!DOCTYPE html>\n", end="")
print("<html lang=\"en\">\n", end="")
print("<head>\n", end="")
# print("    <base href=\"/template3/\">\n", end="")
print("    <meta charset=\"UTF-8\">\n", end="")
print("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n", end="")
print("    <title>Sleeky Pro - Premium Photography & Nature</title>\n", end="")
print("    <link rel=\"stylesheet\" href=\"templatemo-sleeky-pro.css\">\n", end="")
print("\n", end="")
print("</head>\n", end="")
print("<body>\n", end="")
print("    \n", end="")
print("    <header class=\"header\" id=\"header\">\n", end="")
print("        <nav class=\"nav-container\">\n", end="")
print("            <a href=\"#home\" class=\"logo-container\">\n", end="")
print("                <svg class=\"logo-svg\" viewBox=\"0 0 100 100\" xmlns=\"http://www.w3.org/2000/svg\">\n", end="")
print("                    <defs>\n", end="")
print("                        <linearGradient id=\"logoGradient\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n", end="")
print("                            <stop offset=\"0%\" style=\"stop-color:#FF6B6B\"/>\n", end="")
print("                            <stop offset=\"100%\" style=\"stop-color:#7FFFD4\"/>\n", end="")
print("                        </linearGradient>\n", end="")
print("                    </defs>\n", end="")
print("                    <circle cx=\"50\" cy=\"50\" r=\"45\" fill=\"url(#logoGradient)\" opacity=\"0.1\"/>\n", end="")
print("                    <path d=\"M20 60 L35 40 L50 55 L65 35 L80 50\" stroke=\"url(#logoGradient)\" stroke-width=\"4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n", end="")
print("                    <circle cx=\"35\" cy=\"40\" r=\"3\" fill=\"url(#logoGradient)\"/>\n", end="")
print("                    <circle cx=\"50\" cy=\"55\" r=\"3\" fill=\"url(#logoGradient)\"/>\n", end="")
print("                    <circle cx=\"65\" cy=\"35\" r=\"3\" fill=\"url(#logoGradient)\"/>\n", end="")
print("                    <rect x=\"25\" y=\"65\" width=\"50\" height=\"125\" rx=\"7\" fill=\"url(#logoGradient)\" opacity=\"0.3\"/>\n", end="")
print("                </svg>\n", end="")
print("                <span class=\"logo-text\">Sleeky Pro</span>\n", end="")
print("            </a>\n", end="")
print("            <ul class=\"nav-menu\" id=\"navMenu\">\n", end="")
print("                <li><a href=\"#home\" class=\"nav-link active\">Home</a></li>\n", end="")
print("                <li><a href=\"#services\" class=\"nav-link\">Services</a></li>\n", end="")
print("                <li><a href=\"#about\" class=\"nav-link\">About</a></li>\n", end="")
print("                <li><a href=\"#contact\" class=\"nav-link\">Contact</a></li>\n", end="")
print("            </ul>\n", end="")
print("            <button class=\"hamburger\" id=\"hamburger\">\n", end="")
print("                <span></span>\n", end="")
print("                <span></span>\n", end="")
print("                <span></span>\n", end="")
print("            </button>\n", end="")
print("        </nav>\n", end="")
print("    </header>\n", end="")
print("\n", end="")
print("    \n", end="")
print("    <section id=\"home\" class=\"hero\">\n", end="")
print("        <div class=\"slider-container\">\n", end="")
print("            <div class=\"progress-ring\">\n", end="")
print("                <div class=\"progress-bar\" id=\"progressBar\"></div>\n", end="")
print("            </div>\n", end="")
print("            \n", end="")
print("            <div class=\"slider-stage\" id=\"sliderStage\"></div>\n", end="")
print("            \n", end="")
print("            \n", end="")
print("            <div class=\"text-overlay\" id=\"textOverlay\">\n", end="")
print("                <h2 class=\"slide-title\" id=\"slideTitle\">Mountain Peak</h2>\n", end="")
print("                <p class=\"slide-description\" id=\"slideDescription\">Majestic snow-capped mountains reaching towards the endless sky, showcasing nature's raw beauty and power.</p>\n", end="")
print("            </div>\n", end="")
print("            \n", end="")
print("            <button class=\"nav-arrow prev\" id=\"prevArrow\" aria-label=\"Previous\"></button>\n", end="")
print("            <button class=\"nav-arrow next\" id=\"nextArrow\" aria-label=\"Next\"></button>\n", end="")
print("            \n", end="")
print("            <div class=\"controls\">\n", end="")
print("                <button class=\"control-btn play-pause-btn\" id=\"playPauseBtn\" title=\"Play/Pause\">\n", end="")
print("                    <span class=\"play-icon\"></span>\n", end="")
print("                    <span class=\"pause-icon\"></span>\n", end="")
print("                </button>\n", end="")
print("            </div>\n", end="")
print("            \n", end="")
print("            <div class=\"dots\" id=\"dots\"></div>\n", end="")
print("            <div class=\"thumbnails-container\" id=\"thumbnails\"></div>\n", end="")
print("        </div>\n", end="")
print("    </section>\n", end="")
print("\n", end="")
print("    \n", end="")
print("    <section id=\"services\" class=\"section services\">\n", end="")
print("        <div class=\"section-container\">\n", end="")
print("            <div class=\"section-header\">\n", end="")
print("                <h2 class=\"section-title\">Our Services</h2>\n", end="")
print("                <p class=\"section-subtitle\">Advanced photography solutions powered by cutting-edge technology and unmatched expertise in extreme environments.</p>\n", end="")
print("            </div>\n", end="")
print("            \n", end="")
print("            <div class=\"services-container\">\n", end="")
print("                <div class=\"services-tabs\">\n", end="")
print("                    <div class=\"service-tab active\" data-service=\"photography\">\n", end="")
print("                        <span class=\"service-tab-icon\">📸</span>\n", end="")
print("                        <h3>Cinematic Photography</h3>\n", end="")
print("                        <p>Ultra-high resolution captures</p>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"service-tab\" data-service=\"expeditions\">\n", end="")
print("                        <span class=\"service-tab-icon\">🏔️</span>\n", end="")
print("                        <h3>Alpine Expeditions</h3>\n", end="")
print("                        <p>Extreme altitude adventures</p>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"service-tab\" data-service=\"prints\">\n", end="")
print("                        <span class=\"service-tab-icon\">🎨</span>\n", end="")
print("                        <h3>Fine Art Prints</h3>\n", end="")
print("                        <p>Museum-grade collections</p>\n", end="")
print("                    </div>\n", end="")
print("                </div>\n", end="")
print("    <section id=\"about\" class=\"section about\">\n", end="")
print("        <div class=\"section-container\">\n", end="")
print("            <div class=\"section-header\">\n", end="")
print("                <h2 class=\"section-title\">The Future of Nature Photography</h2>\n", end="")
print("                <p class=\"section-subtitle\">Where cutting-edge technology meets artistic vision to document Earth's most extraordinary landscapes.</p>\n", end="")
print("            </div>\n", end="")
print("            \n", end="")
print("            <div class=\"about-grid\">\n", end="")
print("                <div class=\"about-timeline\">\n", end="")
print("                    <div class=\"timeline-line\"></div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"timeline-item\">\n", end="")
print("                        <div class=\"timeline-dot\"></div>\n", end="")
print("                        <div class=\"timeline-year\">2009</div>\n", end="")
print("                        <div class=\"timeline-title\">Genesis in the Rockies</div>\n", end="")
print("                        <div class=\"timeline-description\">21-day solo expedition through Canadian Rockies. Documented climate change effects on alpine glaciers using early digital medium format systems.</div>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"timeline-item\">\n", end="")
print("                        <div class=\"timeline-dot\"></div>\n", end="")
print("                        <div class=\"timeline-year\">2015</div>\n", end="")
print("                        <div class=\"timeline-title\">National Geographic Recognition</div>\n", end="")
print("                        <div class=\"timeline-description\">First photographer to capture Aurora Borealis from 14,000+ feet elevation. Featured on National Geographic cover for breakthrough high-altitude night photography.</div>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"timeline-item\">\n", end="")
print("                        <div class=\"timeline-dot\"></div>\n", end="")
print("                        <div class=\"timeline-year\">2019</div>\n", end="")
print("                        <div class=\"timeline-title\">Smithsonian Acquisition</div>\n", end="")
print("                        <div class=\"timeline-description\">Three-piece collection acquired by Smithsonian Institution. Pioneered \"patience photography\" - waiting 72+ hours in extreme conditions for perfect conditions.</div>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"timeline-item\">\n", end="")
print("                        <div class=\"timeline-dot\"></div>\n", end="")
print("                        <div class=\"timeline-year\">2024</div>\n", end="")
print("                        <div class=\"timeline-title\">AI-Enhanced Workflow</div>\n", end="")
print("                        <div class=\"timeline-description\">Revolutionary integration of AI weather prediction and machine learning for optimal capture timing. Reducing expedition failure rate to under 5%.</div>\n", end="")
print("                    </div>\n", end="")
print("                </div>\n", end="")
print("                \n", end="")
print("                <div class=\"about-tech\">\n", end="")
print("                    <div class=\"tech-card\">\n", end="")
print("                        <div class=\"tech-icon\">🤖</div>\n", end="")
print("                        <div class=\"tech-title\">AI Weather Intelligence</div>\n", end="")
print("                        <div class=\"tech-description\">Proprietary algorithms analyze 15+ meteorological data sources to predict optimal shooting windows with 94% accuracy up to 72 hours in advance.</div>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"tech-card\">\n", end="")
print("                        <div class=\"tech-icon\">🛰️</div>\n", end="")
print("                        <div class=\"tech-title\">Satellite Reconnaissance</div>\n", end="")
print("                        <div class=\"tech-description\">Real-time satellite imagery integration allows dynamic route planning and hazard avoidance during expeditions to previously inaccessible locations.</div>\n", end="")
print("                    </div>\n", end="")
print("                    \n", end="")
print("                    <div class=\"tech-card\">\n", end="")
print("                        <div class=\"tech-icon\">🎯</div>\n", end="")
print("                        <div class=\"tech-title\">Precision Capture Systems</div>\n", end="")
print("                        <div class=\"tech-description\">Sub-millimeter camera positioning using GPS-guided stabilization systems ensures perfect composition even in 80+ mph mountain winds.</div>\n", end="")
print("                    </div>\n", end="")
print("                </div>\n", end="")
print("            </div>\n", end="")



print("</body>\n", end="")
print("</html>", end="")

