
server {
    listen 127.0.0.1:8081;
    root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
    index index.html index.py;
    client_max_body_size 1;
    error_page 403 400 402 403 405 404 /custom_50x.html;
    location / {
        root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
        autoindex on;
    }

    location /test_post
    {
        alias /workspaces/The-Fastest-Http-Server/websites/test_post/;
        allow_methods  POST ;
    }

    location /cgi-bin
    {
        allow_methods GET POST DELETE;
        root /workspaces/The-Fastest-Http-Server/;
        cgi_pass .py /opt/conda/bin/python;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8082;
    root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
    index index.html index.py;
    client_max_body_size 1;
    error_page 403 400 402 403 405 404 /custom_50x.html;
    location / {
        root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
        autoindex on;
    }

    location /test_post
    {
        alias /workspaces/The-Fastest-Http-Server/websites/test_post/;
        allow_methods  POST ;
    }

    location /cgi-bin
    {
        allow_methods GET POST DELETE;
        root /workspaces/The-Fastest-Http-Server/;
        cgi_pass .py /opt/conda/bin/python;
        autoindex on;
    }
}
server {
    listen 127.0.0.1:8083;
    root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
    index index.html index.py;
    client_max_body_size 1;
    error_page 403 400 402 403 405 404 /custom_50x.html;
    location / {
        root /workspaces/The-Fastest-Http-Server/websites/TemplateSite/template4;
        autoindex on;
    }

    location /test_post
    {
        alias /workspaces/The-Fastest-Http-Server/websites/test_post/;
        allow_methods  POST ;
    }

    location /cgi-bin
    {
        allow_methods GET POST DELETE;
        root /workspaces/The-Fastest-Http-Server/;
        cgi_pass .py /opt/conda/bin/python;
        autoindex on;
    }
}