
	server {
	    listen 0.0.0.0:8082;

		root /home/mjaouchi/Desktop/Webserv;
		# index /index.html;
		error_page 404 /errorPage/404.html;
		# return 18446744073709551917 websites;

		client_max_body_size 100;

		location / {
			autoindex on;
			client_max_body_size 1;
			allow_methods GET POST DELETE;

			cgi_pass .py /usr/bin/python3;
			upload_location /;
	        upload_store /home/mjaouchi/Desktop/Webserv;
			# autoindex on;
		}
		index index.html;

	}

 
