server {
    listen 127.0.0.1:8081;
    # تأكد من أن المسار صحيح وإملائي
    root /workspaces/The-Fastest-Http-Server; 
    
    # استخدام ملف سجل واحد وتحديد حجم منطقي
    # access_log log_8080.txt;
    client_max_body_size 10m;
    location / {
        autoindex on;
        allow_methods GET;
        # index testCase.php index2.html;
    }
#    location /test {
#     # alias /workspaces/The-Fastest-Http-Server;
#     root /workspaces/The-Fastest-Http-Server;
#         return 200 "Hello from /test endpoint!";
#         # index index.html testCase.py;
#     }

    location /test
    {
        return  301 "Hello from /test endpoint!";
        cgi_pass .py /usr/local/python/3.12.1/bin/python;
    }
}

