server {
    # 1. Basic Connection Setup
    listen 127.0.0.1:8080;

    # 2. Global Rules (Fallback)
    root ./www/html;
    index index.html index.php;
    client_max_body_size 10000000; # 10 MB

    # 3. Error Page Customization
    error_page 404 /custom_404.html;
    error_page 500 502 503 /custom_50x.html;

    # --- Routes (Location Blocks) ---

    # A. Default Route
    location / {
        allow_methods GET POST;
        autoindex off;
    }

    # B. Directory Listing & Uploads
    location /test {
        allow_methods GET POST DELETE;
        root /workspaces/The-Fastest-Http-Server;
        autoindex on;       # Shows file list if no index found
        upload_store uploads_temp; # Where to save POSTed files
        return 301 https://www.google.com;
    }

    # C. Redirection
    location /google {
        return 301 https://www.google.com/;
    }

    # D. CGI Execution (The complex part)
    location /cgi-bin {
        root ./www/scripts;
        allow_methods GET POST;
        index time.py time.html;
        
        # Mapping extension -> Executable
        cgi_pass .py /usr/bin/python3;
    }
    
    # E. The weird "kapouet" example from subject
    location /kapouet {
        root /tmp/www;
    }
}
