server {
    # 1. Basic Connection Setup
    listen 127.0.0.1:8080;
    root /workspaces/The-Fastest-Http-Server/website;
    # --- Routes (Location Blocks) ---

    # A. Default Route
    location / {
        root /etc;
    }

}